import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Nunito_Sans} from 'next/font/google'
import { Sidebar } from "./components/sidebar/sidebar";

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <div className="">
        <Sidebar />
        </div>
        {children}
      </body>
    </html>
  );
}
